# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\2020-11-24\project\UI_3.0\111boundaryUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from ..BC.boundaryeditUI import *
from PyQt5.QtCore import *

# Sim_mod = "laminar"
# Tur_mod = "laminar"

para_dirt = {
    "laminar":
    {
        "laminar":["U:","p:"]
    },
    "RAS":
    {
        'kEpsilon':["U:","p:","k:","epsilon:","nut:"],
        'kOmegaSST':["U:","p:","k:","omega:","nut:"],
        'SpalartAllmaras':["U:","p:","nuTilda:","nut:"],
        'LaunderSharmaKE':["U:","p:","k:","epsilon:","nut:"],
    },
    "LES":
    {
        'kEqn':["U:","p:","k:","epsilon:","nut:"],
        'SpalartAllmarasDDES':["U:","p:","k:","nut:"],
        'Smagorinsky':["U:","p:","k:","nut:"],
    }
}



class boundary_edit_form(QDialog):
    def __init__(self): 
        super(boundary_edit_form, self).__init__() 
        self.boundaryform_1 = Ui_Form()
        self.boundaryform_2 = Ui_Form()
        self.boundaryform_3 = Ui_Form()
        self.boundaryform_4 = Ui_Form()
        self.boundaryform_5 = Ui_Form()
        self.boundary_wid_1 = QtWidgets.QFrame()
        self.boundary_wid_1.setFrameShadow(QFrame.Sunken)
        self.boundary_wid_1.setLineWidth(3)
        self.boundary_wid_1.setMidLineWidth(3)                  
        self.boundary_wid_1.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
        
        self.boundary_wid_2 = QtWidgets.QFrame()
        self.boundary_wid_2.setFrameShadow(QFrame.Sunken)
        self.boundary_wid_2.setLineWidth(3)
        self.boundary_wid_2.setMidLineWidth(3)                  
        self.boundary_wid_2.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
        self.boundary_wid_3 = QtWidgets.QFrame()
        self.boundary_wid_3.setFrameShadow(QFrame.Sunken)
        self.boundary_wid_3.setLineWidth(3)
        self.boundary_wid_3.setMidLineWidth(3)                  
        self.boundary_wid_3.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
        self.boundary_wid_4 = QtWidgets.QFrame()
        self.boundary_wid_4.setFrameShadow(QFrame.Sunken)
        self.boundary_wid_4.setLineWidth(3)
        self.boundary_wid_4.setMidLineWidth(3)                  
        self.boundary_wid_4.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
        self.boundary_wid_5 = QtWidgets.QFrame()
        self.boundary_wid_5.setFrameShadow(QFrame.Sunken)
        self.boundary_wid_5.setLineWidth(3)
        self.boundary_wid_5.setMidLineWidth(3)                  
        self.boundary_wid_5.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)           
        self.boundary_wid_1.setSizePolicy(sizePolicy)
        self.boundary_wid_2.setSizePolicy(sizePolicy)
        self.boundary_wid_3.setSizePolicy(sizePolicy)
        self.boundary_wid_4.setSizePolicy(sizePolicy)
        self.boundary_wid_5.setSizePolicy(sizePolicy)
        self.Ui_wid_list = [self.boundary_wid_1,self.boundary_wid_2,
            self.boundary_wid_3,self.boundary_wid_4,self.boundary_wid_5]

        self.Ui_Form_list = [self.boundaryform_1,self.boundaryform_2,
            self.boundaryform_3,self.boundaryform_4,self.boundaryform_5]

    def setupUi(self, Form, model = "laminar", turbulence_model = "laminar"):
        Form.setObjectName("Form")
        Form.resize(513, 392)
        Sim_mod = model
        Tur_mod = turbulence_model
        self.para_list = para_dirt[Sim_mod][Tur_mod] 
        self.horizontalLayout = QtWidgets.QVBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        # 转移边界类型至此
        self.boundary_type_lay = QtWidgets.QHBoxLayout()
        self.boundary_type_label = QtWidgets.QLabel('边界条件类型')
        self.boundary_type_label.setFixedHeight(40)
        self.boundarytype = QtWidgets.QComboBox()
        self.boundarytype.setFixedHeight(40)
        self.boundarytype.addItem('patch')
        self.boundarytype.addItem('wall')
        self.boundarytype.addItem('symmetryPlane')
        self.boundarytype.addItem('symmetry')
        self.boundarytype.addItem('empty')
        self.boundarytype.addItem('wedge')
        self.boundarytype.addItem('cyclic')
        self.boundarytype.addItem('cyclicAMI')
        self.boundary_type_lay.addWidget(self.boundary_type_label)
        self.boundary_type_lay.addWidget(self.boundarytype)
        self.horizontalLayout.addLayout(self.boundary_type_lay)
        self.horizontalLayout.addWidget(self.scrollArea)
        # self.formLayout.addRow('items',self.boundaryform)
        for i,items in enumerate(self.para_list):
            self.frame = QtWidgets.QFrame()
            self.ver = QtWidgets.QVBoxLayout(self.frame)
            self.frame.setFrameShadow(QFrame.Sunken)
            self.frame.setLineWidth(3)
            self.frame.setMidLineWidth(3)                  
            self.frame.setFrameStyle(QFrame.WinPanel|QFrame.Raised)
            self.label = QLabel(self.frame)
            self.ver.addWidget(self.label) 
            self.label.setText(items)
            sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
            sizePolicy.setHorizontalStretch(1)
            sizePolicy.setVerticalStretch(0)
            sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())            
            self.label.setSizePolicy(sizePolicy)
            self.Ui_Form_list[i].setupUi(self.Ui_wid_list[i])
            self.gridLayout.addWidget(self.frame,i,0)
            self.gridLayout.addWidget(self.Ui_wid_list[i],i,1)

        self.buttonBox = QtWidgets.QDialogButtonBox(Form)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(
                QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.accepted.connect(Form.accept)
        self.buttonBox.rejected.connect(Form.reject)
        self.horizontalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))


if __name__ == '__main__':  
    app = QApplication(sys.argv) 
    MainDialog = QDialog() 
    myDialog = boundary_edit_form()
    myDialog.setupUi(MainDialog)
    MainDialog.show()
    sys.exit(app.exec_()) 
