# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\NSCC\UI\Material\MaterialManager.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5 import QtCore, QtGui, QtWidgets
from ..Material.MaterialEdit import Ui_Mat_Edi
from ..commonfunction import *
class Ui_Mat_Man(object):
    def __init__(self,working_dir_name = None,pimplefoam_root = None):
        super(Ui_Mat_Man, self).__init__()
        self.subDialog = QDialog()
        self.pimplefoam_root = pimplefoam_root
        self.working_dir_name = working_dir_name
        self.Mat_Edi = Ui_Mat_Edi() 
        self.Mat_Edi.setupUi(self.subDialog,self.working_dir_name,self.pimplefoam_root)        
        self.setupUi
        
    def setupUi(self, Material):
        Material.setObjectName("Material")
        Material.resize(699, 310)
        self.widget = QtWidgets.QWidget(Material)
        self.widget.setGeometry(QtCore.QRect(0, 0, 691, 301))
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 681, 291))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.widget_2 = QtWidgets.QWidget(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 111, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.widget_2)
        self.pushButton_3.clicked.connect(self.pop_mat_edi)
        self.pushButton_2.clicked.connect(self.pop_mat_edi)
        self.pushButton.clicked.connect(Material.reject)
        self.retranslateUi(Material)
        QtCore.QMetaObject.connectSlotsByName(Material)

    def retranslateUi(self, Material):
        _translate = QtCore.QCoreApplication.translate
        Material.setWindowTitle(_translate("Material", "材料选择"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Material", "材料名称"))
        self.pushButton_3.setText(_translate("Material", "创建"))
        self.pushButton_2.setText(_translate("Material", "编辑"))
        self.pushButton.setText(_translate("Material", "确定"))

    def pop_mat_edi(self):
        self.subDialog.show()
        self.Mat_Edi.buttonBox.accepted.connect(self.read_to_Man)

    def read_to_Man(self):

        info_name_list = ["材料名称",self.Mat_Edi.formLayout.itemAt(1,0).widget().text()]
        info_value_list = [self.Mat_Edi.formLayout.itemAt(0,1).widget().text(),
                                self.Mat_Edi.formLayout.itemAt(1,1).widget().currentText()]

        for col_num in range(2,int(self.Mat_Edi.formLayout.count()/2)):
            info_name_list.append(self.Mat_Edi.formLayout.itemAt(col_num,0).widget().text().strip(':'))
            info_value_list.append(self.Mat_Edi.formLayout.itemAt(col_num,1).widget().text())

        for index,name in enumerate(info_name_list):       
            self.tableWidget.setColumnCount(len(info_name_list))
            self.tableWidget.setRowCount(1)
            self.tableWidget.setHorizontalHeaderLabels(info_name_list)
            newItem= QTableWidgetItem (info_value_list[index])
            self.tableWidget.setItem(0,index,newItem)

        #save to json
        save_to_json(self.working_dir_name,'material',info_name_list,info_value_list)

    def reload(self,dictionary):        
        info_name_list = list(dictionary['material'].keys())
        info_value_list = list(dictionary['material'].values())
        for index,name in enumerate(info_name_list):       
            self.tableWidget.setColumnCount(len(info_name_list))
            self.tableWidget.setRowCount(1)
            self.tableWidget.setHorizontalHeaderLabels(info_name_list)
            newItem= QTableWidgetItem (info_value_list[index])
            self.tableWidget.setItem(0,index,newItem)



if __name__ == '__main__':  
    import sys  
    app = QApplication(sys.argv)  
    MainDialog = QDialog() 
    myWindow = Ui_Mat_Man()  
    myWindow.setupUi(MainDialog) 
    MainDialog.show()
    sys.exit(app.exec_()) 

