# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\NSCC\UI\Material\MaterialEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from ..commonfunction import *


# pimplefoam_root = '/usr/sw-cluster/simforge/PFsalome/SALOME-9.4.0-CO7-SRC/BINARIES-CO7/ASTERSTUDY/lib/python3.6/site-packages/asterstudy'
# working_dir_name = '/usr/sw-cluster/simforge/PFsalome/SALOME-9.4.0-CO7-SRC/BINARIES-CO7/ASTERSTUDY/lib/python3.6/site-packages/asterstudy/workingdirectory'

class Ui_Mat_Edi(object):
    def __init__(self):
        super(Ui_Mat_Edi, self).__init__()
        self.setupUi
    def setupUi(self, Dialog,working_dir_name = None,pimplefoam_root = None):
        Dialog.setObjectName("Dialog")
        Dialog.resize(444, 224)
        self.pimplefoam_root = pimplefoam_root
        self.working_dir_name = working_dir_name
        self.formLayoutWidget = QtWidgets.QWidget(Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(69, 39, 351, 170))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(14)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setMinimumSize(QtCore.QSize(0, 40))
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit.setMinimumSize(QtCore.QSize(0, 40))
        self.LineEdit.setObjectName("LineEdit")
        self.LineEdit.setText('(e.g. Air)')
        self.LineEdit.setClearButtonEnabled(True)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_2.setMinimumSize(QtCore.QSize(0, 40))
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 40))
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)
        self.comboBox.addItem('请选择')
        self.comboBox.addItem('Newtonian')
        self.comboBox.addItem('BirdCarreau')
        self.comboBox.addItem('CrossPowerLaw')
        self.comboBox.addItem('PowerLaw')
        self.comboBox.addItem('Casson')

        self.retranslateUi(Dialog)        
        self.comboBox.currentIndexChanged['int'].connect(self.rm_item)

        # self.add_item(Dialog)
        self.comboBox.currentIndexChanged['int'].connect(lambda:self.add_item(Dialog))
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.formLayout.setSizeConstraint(QLayout.SetFixedSize)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
        # add signal
        self.buttonBox.accepted.connect(self.collect_material_res)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "材料设置"))
        self.Label.setText(_translate("Dialog", "  流体名称：  "))
        self.Label_2.setText(_translate("Dialog", "  流变模型：  "))

    def rm_item(self):
        while self.formLayout.count() != 4:
            self.formLayout.removeRow(2)

    def add_item(self, Dialog):
        if self.comboBox.currentIndex() == 0:
            Dialog.resize(444, 224)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)                
        if self.comboBox.currentIndex() == 1:
            self.LineEdit_2 = QtWidgets.QLineEdit()
            self.LineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
            self.LineEdit_2.setText('1e-4')            
            self.formLayout.addRow('    nu:', self.LineEdit_2)
            Dialog.resize(444, 284)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)
        if self.comboBox.currentIndex() == 2:
            self.addLineEdit = QtWidgets.QLineEdit()
            self.addLineEdit.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_2 = QtWidgets.QLineEdit()
            self.addLineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_3 = QtWidgets.QLineEdit()
            self.addLineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_4 = QtWidgets.QLineEdit()
            self.addLineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
            self.formLayout.addRow('    nu0:', self.addLineEdit)
            self.formLayout.addRow('    nulnf:', self.addLineEdit_2)
            self.formLayout.addRow('    k:', self.addLineEdit_3)
            self.formLayout.addRow('    n:', self.addLineEdit_4)
            Dialog.resize(444, 454)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)
        if self.comboBox.currentIndex() == 3:
            self.addLineEdit = QtWidgets.QLineEdit()
            self.addLineEdit.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_2 = QtWidgets.QLineEdit()
            self.addLineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_3 = QtWidgets.QLineEdit()
            self.addLineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_4 = QtWidgets.QLineEdit()
            self.addLineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
            self.formLayout.addRow('    nu0:', self.addLineEdit)
            self.formLayout.addRow('    nulnf:', self.addLineEdit_2)
            self.formLayout.addRow('    m:', self.addLineEdit_3)
            self.formLayout.addRow('    n:', self.addLineEdit_4)
            Dialog.resize(444, 454)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)
        if self.comboBox.currentIndex() == 4:
            self.addLineEdit = QtWidgets.QLineEdit()
            self.addLineEdit.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_2 = QtWidgets.QLineEdit()
            self.addLineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_3 = QtWidgets.QLineEdit()
            self.addLineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_4 = QtWidgets.QLineEdit()
            self.addLineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
            self.formLayout.addRow('    nuMax:', self.addLineEdit)
            self.formLayout.addRow('    nuMin:', self.addLineEdit_2)
            self.formLayout.addRow('    k:', self.addLineEdit_3)
            self.formLayout.addRow('    n:', self.addLineEdit_4)
            Dialog.resize(444, 454)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)
        if self.comboBox.currentIndex() == 5:
            self.addLineEdit = QtWidgets.QLineEdit()
            self.addLineEdit.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_2 = QtWidgets.QLineEdit()
            self.addLineEdit_2.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_3 = QtWidgets.QLineEdit()
            self.addLineEdit_3.setMinimumSize(QtCore.QSize(0, 40))
            self.addLineEdit_4 = QtWidgets.QLineEdit()
            self.addLineEdit_4.setMinimumSize(QtCore.QSize(0, 40))
            self.formLayout.addRow('    nu0:', self.addLineEdit)
            self.formLayout.addRow('    tau0:', self.addLineEdit_2)
            self.formLayout.addRow('    nuMax:', self.addLineEdit_3)
            self.formLayout.addRow('    nuMin:', self.addLineEdit_4)
            Dialog.resize(444, 454)
            self.buttonBox.setGeometry(190,Dialog.geometry().height()-80,200,100)    

    # collect material data 
    def collect_material_res(self):
        initfile(self.working_dir_name + '/constant/transportProperties',self.pimplefoam_root + '/alternativefile/constant/laminar/transportProperties')
        value_1 = self.formLayout.itemAt(1,1).widget().currentText()
        label_1 = self.formLayout.itemAt(1,0).widget().text()
        changefile(self.working_dir_name + '/constant/transportProperties',label_1,value_1)
        for col_num in range(2,int(self.formLayout.count()/2)):
            label_2 = self.formLayout.itemAt(col_num,0).widget().text().strip(':')
            label_2 = label_2.lstrip()
            if 'nu' in label_2:
                unit = '[0 2 -1 0 0 0 0]'
            if label_2 == "k":
                unit += '[0 0 1 0 0 0 0]'
            if label_2 == "n":
                unit += '[0 0 0 0 0 0 0]'
            if label_2 == "m":
                unit += '[0 0 1 0 0 0 0]'
            if label_2 == "tau0":
                unit += '[0 0 0 0 0 0 0]'
            value_2 = self.formLayout.itemAt(col_num,1).widget().text()
            addfile(self.working_dir_name + '/constant/transportProperties',label_2,unit,value_2 + ';'+'\n')




if __name__ == '__main__':  
    import sys  
    app = QApplication(sys.argv) 
    MainDialog = QDialog() 
    myWindow = Ui_Mat_Edi()  
    myWindow.setupUi(MainDialog) 
    MainDialog.show()
    sys.exit(app.exec_()) 

